name: CI/CD

on:
  push:
    branches:
      - main


  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Install ngrok
        run: |
          curl -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok.zip
          chmod +x ngrok
          sudo mv ngrok /usr/local/bin/ngrok
          rm ngrok.zip
          
      - name: Start Ngrok
        run: |
          ngrok http 5095 > /dev/null &
          sleep 5
          export NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV

          
      - name: Check Docker Version
        run: docker --version
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build . -t cunjak/tool-pedia:latest

      - name: Push Docker image
        run: |
          docker login -u cunjak -p ${{ secrets.DOCKER_PASSWORD }}
          docker push cunjak/tool-pedia:latest
          
      - name: Trigger Deployment to Webhook Server
        run: |
          NGROK_URL=${{ env.NGROK_URL }}
          curl -X POST $NGROK_URL/webhook -H "Authorization: Bearer ${{ secrets.Token }}"
